# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- Containerization

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(e52f744d-5933-4c15-899b-8229737e4d75)'
    azureContainerRegistry: '{"loginServer":"acreast.azurecr.io", "id" : "/subscriptions/e52f744d-5933-4c15-899b-8229737e4d75/resourceGroups/acr-grp/providers/Microsoft.ContainerRegistry/registries/acreast"}'
    dockerComposeFile: /home/vsts/work/1/compose.yaml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker compose build'
